[build]
  command = "pip3 install -r requirements.txt && python manage.py collectstatic --noinput && npm run build"
  publish = build

[build.environment]
  DJANGO_SETTINGS_MODULE = "mysite.settings"
  PYTHON_VERSION = "3.8"
  NODE_VERSION = "18.20.3"

[context.production.environment]
  DEBUG = "False"
