# Generated by Django 5.0 on 2024-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hadith', models.TextField()),
                ('book_taken_from', models.CharField(max_length=100)),
                ('hadith_grading', models.CharField(max_length=100)),
            ],
        ),
    ]
